name: Build BattleRoyale (Paper 1.21.7)
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: mvn -q -U -e -DskipTests clean package
      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: BattleRoyale-jar
          path: target/BattleRoyale-0.1.jar
